use std::sync::mpsc;
use std::sync::Mutex;
use x11rb::atom_manager;
use x11rb::connection::Connection;
use x11rb::protocol::xproto::*;
use x11rb::protocol::Event;
use x11rb::rust_connection::RustConnection;
use x11rb::wrapper::ConnectionExt as _;

use crate::IpcCommand;

const SYSTEM_TRAY_REQUEST_DOCK: u32 = 0;
const XEMBED_MAPPED: u32 = 1;
const ICON_SIZE: u16 = 24;

// ── Popup menu constants ────────────────────────────────────────────────
const MENU_ITEMS: &[(&str, MenuAction)] = &[
    ("Copy Last", MenuAction::CopyLast),
    ("Toggle", MenuAction::Toggle),
    ("Exit", MenuAction::Exit),
];
const MENU_ITEM_HEIGHT: u16 = 22;
const MENU_PAD_X: i16 = 10;
const MENU_PAD_TOP: i16 = 4;
const MENU_WIDTH: u16 = 100;

#[derive(Clone, Copy)]
enum MenuAction {
    CopyLast,
    Toggle,
    Exit,
}

// Pre-rendered 24x24 RGBA icons (generated by assets/gen_icons.py).
const ICON_IDLE: &[u8] = include_bytes!("../assets/idle.rgba");
const ICON_SLEEPING: &[u8] = include_bytes!("../assets/sleeping.rgba");
const ICON_LISTENING: &[u8] = include_bytes!("../assets/listening.rgba");
const ICON_DICTATING: &[u8] = include_bytes!("../assets/dictating.rgba");
const ICON_RECORDING: &[u8] = include_bytes!("../assets/recording.rgba");
const ICON_PROCESSING: &[u8] = include_bytes!("../assets/processing.rgba");
const ICON_RECORDING_PROCESSING: &[u8] = include_bytes!("../assets/recording_processing.rgba");

atom_manager! {
    pub Atoms: AtomsCookie {
        _NET_SYSTEM_TRAY_OPCODE,
        _NET_SYSTEM_TRAY_S0,
        _XEMBED_INFO,
        MANAGER,
    }
}

#[derive(Clone, Copy, PartialEq)]
pub enum TrayStatus {
    Idle,
    Sleeping,
    Listening,
    Dictating,
    Recording,
    Processing,
    RecordingProcessing,
}

fn icon_rgba(status: TrayStatus) -> &'static [u8] {
    match status {
        TrayStatus::Idle => ICON_IDLE,
        TrayStatus::Sleeping => ICON_SLEEPING,
        TrayStatus::Listening => ICON_LISTENING,
        TrayStatus::Dictating => ICON_DICTATING,
        TrayStatus::Recording => ICON_RECORDING,
        TrayStatus::Processing => ICON_PROCESSING,
        TrayStatus::RecordingProcessing => ICON_RECORDING_PROCESSING,
    }
}

/// Composite a premultiplied RGBA icon onto a background color,
/// producing X11 ZPixmap 32bpp little-endian (BGRX) output.
fn composite_icon(icon: &[u8], bg_r: u8, bg_g: u8, bg_b: u8) -> Vec<u8> {
    let mut out = Vec::with_capacity(icon.len());
    for pixel in icon.chunks_exact(4) {
        let (sr, sg, sb, sa) = (pixel[0], pixel[1], pixel[2], pixel[3]);
        let a = sa as f32 / 255.0;
        let inv = 1.0 - a;
        let r = (sr as f32 + bg_r as f32 * inv) as u8;
        let g = (sg as f32 + bg_g as f32 * inv) as u8;
        let b = (sb as f32 + bg_b as f32 * inv) as u8;
        // X11 ZPixmap 32bpp little-endian: B G R pad
        out.push(b);
        out.push(g);
        out.push(r);
        out.push(0xFF);
    }
    out
}

/// Sample the background color by reading one pixel from the cleared window.
fn sample_bg(conn: &RustConnection, win: Window) -> (u8, u8, u8) {
    conn.clear_area(false, win, 0, 0, 0, 0).ok();
    conn.flush().ok();
    if let Some(reply) = conn
        .get_image(ImageFormat::Z_PIXMAP, win, 0, 0, 1, 1, !0u32)
        .ok()
        .and_then(|c| c.reply().ok())
    {
        let d = &reply.data;
        if d.len() >= 3 {
            // ZPixmap little-endian: B G R [A]
            return (d[2], d[1], d[0]);
        }
    }
    (0, 0, 0) // fallback to black
}

// ── X11 tray handle ──────────────────────────────────────────────────────

pub struct TrayHandle {
    status: std::sync::Arc<Mutex<TrayStatus>>,
    repaint_conn: std::sync::Arc<RustConnection>,
    win: Window,
}

impl Clone for TrayHandle {
    fn clone(&self) -> Self {
        Self {
            status: std::sync::Arc::clone(&self.status),
            repaint_conn: std::sync::Arc::clone(&self.repaint_conn),
            win: self.win,
        }
    }
}

impl TrayHandle {
    pub fn update(&self, status: TrayStatus) {
        let mut s = self.status.lock().unwrap();
        if *s != status {
            *s = status;
            drop(s);
            let _ = self.repaint_conn.send_event(
                false,
                self.win,
                EventMask::EXPOSURE,
                ExposeEvent {
                    response_type: x11rb::protocol::xproto::EXPOSE_EVENT,
                    sequence: 0,
                    window: self.win,
                    x: 0,
                    y: 0,
                    width: ICON_SIZE,
                    height: ICON_SIZE,
                    count: 0,
                },
            );
            let _ = self.repaint_conn.flush();
        }
    }

    pub fn shutdown(&self) {
        let _ = self.repaint_conn.destroy_window(self.win);
        let _ = self.repaint_conn.flush();
    }
}

// ── Popup menu ──────────────────────────────────────────────────────────

fn menu_height() -> u16 {
    MENU_ITEM_HEIGHT * MENU_ITEMS.len() as u16
}

/// Map a point inside the menu window to an item index.
fn menu_hit(x: i16, y: i16) -> Option<usize> {
    if x < 0 || x >= MENU_WIDTH as i16 || y < 0 || y >= menu_height() as i16 {
        return None;
    }
    Some((y / MENU_ITEM_HEIGHT as i16) as usize)
}

/// Draw the menu items, highlighting the hovered row.
fn draw_menu(
    conn: &RustConnection,
    win: Window,
    gc_text: Gcontext,
    gc_hl_bg: Gcontext,
    gc_hl_text: Gcontext,
    hover: Option<usize>,
) {
    let _ = conn.clear_area(false, win, 0, 0, MENU_WIDTH, menu_height());
    for (i, (label, _)) in MENU_ITEMS.iter().enumerate() {
        let y_top = i as i16 * MENU_ITEM_HEIGHT as i16;
        let text_y = y_top + MENU_ITEM_HEIGHT as i16 - MENU_PAD_TOP - 2;
        if Some(i) == hover {
            let _ = conn.poly_fill_rectangle(
                win,
                gc_hl_bg,
                &[Rectangle {
                    x: 0,
                    y: y_top,
                    width: MENU_WIDTH,
                    height: MENU_ITEM_HEIGHT,
                }],
            );
            let _ = conn.image_text8(win, gc_hl_text, MENU_PAD_X, text_y, label.as_bytes());
        } else {
            let _ = conn.image_text8(win, gc_text, MENU_PAD_X, text_y, label.as_bytes());
        }
    }
    let _ = conn.flush();
}

/// Show a popup menu at (root_x, root_y). Returns the chosen action, or None
/// if dismissed.  Blocks until the user picks an item or dismisses.
fn show_popup_menu(
    conn: &RustConnection,
    screen: &x11rb::protocol::xproto::Screen,
    root_x: i16,
    root_y: i16,
) -> Option<MenuAction> {
    let height = menu_height();

    // Clamp to screen edges.
    let screen_w = screen.width_in_pixels as i16;
    let screen_h = screen.height_in_pixels as i16;
    let mut x = root_x;
    let mut y = root_y;
    if x + MENU_WIDTH as i16 > screen_w {
        x = screen_w - MENU_WIDTH as i16;
    }
    if y + height as i16 > screen_h {
        y = y - height as i16;
    }
    if x < 0 { x = 0; }
    if y < 0 { y = 0; }

    // Create override-redirect popup window.
    let win = match conn.generate_id() {
        Ok(id) => id,
        Err(_) => return None,
    };
    if conn
        .create_window(
            screen.root_depth,
            win,
            screen.root,
            x,
            y,
            MENU_WIDTH,
            height,
            1, // border width
            WindowClass::INPUT_OUTPUT,
            screen.root_visual,
            &CreateWindowAux::default()
                .override_redirect(1u32)
                .background_pixel(screen.white_pixel)
                .border_pixel(screen.black_pixel)
                .event_mask(
                    EventMask::EXPOSURE
                        | EventMask::BUTTON_PRESS
                        | EventMask::BUTTON_RELEASE
                        | EventMask::POINTER_MOTION
                        | EventMask::KEY_PRESS,
                ),
        )
        .is_err()
    {
        return None;
    }

    // Open a core X11 font and create GCs.
    let font = conn.generate_id().ok();
    let font = match font {
        Some(f) => {
            if conn.open_font(f, b"fixed").is_err() {
                None
            } else {
                Some(f)
            }
        }
        None => None,
    };

    let gc_text = conn.generate_id().unwrap_or(0);
    let gc_hl_bg = conn.generate_id().unwrap_or(0);
    let gc_hl_text = conn.generate_id().unwrap_or(0);

    let mut gc_aux = CreateGCAux::default()
        .foreground(screen.black_pixel)
        .background(screen.white_pixel);
    if let Some(f) = font {
        gc_aux = gc_aux.font(f);
    }
    let _ = conn.create_gc(gc_text, win, &gc_aux);

    let _ = conn.create_gc(
        gc_hl_bg,
        win,
        &CreateGCAux::default().foreground(screen.black_pixel),
    );

    let mut gc_aux2 = CreateGCAux::default()
        .foreground(screen.white_pixel)
        .background(screen.black_pixel);
    if let Some(f) = font {
        gc_aux2 = gc_aux2.font(f);
    }
    let _ = conn.create_gc(gc_hl_text, win, &gc_aux2);

    let _ = conn.map_window(win);
    let _ = conn.flush();

    // Grab pointer so clicks outside dismiss the menu.
    let grab_ok = conn
        .grab_pointer(
            true,
            win,
            (EventMask::BUTTON_PRESS
                | EventMask::BUTTON_RELEASE
                | EventMask::POINTER_MOTION)
                .into(),
            GrabMode::ASYNC,
            GrabMode::ASYNC,
            x11rb::NONE,
            x11rb::NONE,
            x11rb::CURRENT_TIME,
        )
        .ok()
        .and_then(|c| c.reply().ok())
        .map(|r| r.status == GrabStatus::SUCCESS)
        .unwrap_or(false);

    // Grab keyboard for Escape.
    let _ = conn.grab_keyboard(
        true,
        win,
        x11rb::CURRENT_TIME,
        GrabMode::ASYNC,
        GrabMode::ASYNC,
    );
    let _ = conn.flush();

    // Look up Escape keycode from the keyboard mapping.
    let escape_keycode = {
        let setup = conn.setup();
        let min_kc = setup.min_keycode;
        let max_kc = setup.max_keycode;
        let mut esc = 9u8; // common default
        if let Ok(cookie) = conn.get_keyboard_mapping(min_kc, max_kc - min_kc + 1) {
            if let Ok(mapping) = cookie.reply() {
                let per = mapping.keysyms_per_keycode as usize;
                for kc in min_kc..=max_kc {
                    let off = (kc - min_kc) as usize * per;
                    if mapping.keysyms.get(off) == Some(&0xFF1B) {
                        esc = kc;
                        break;
                    }
                }
            }
        }
        esc
    };

    // Nested event loop.
    let mut hover: Option<usize> = None;
    let mut first_release = true; // skip the release from the opening click
    let result = loop {
        let event = match conn.wait_for_event() {
            Ok(e) => e,
            Err(_) => break None,
        };
        match event {
            Event::Expose(ev) if ev.window == win && ev.count == 0 => {
                draw_menu(conn, win, gc_text, gc_hl_bg, gc_hl_text, hover);
            }
            Event::MotionNotify(ev) => {
                // Translate root coords to menu-local coords.
                let lx = ev.root_x - x;
                let ly = ev.root_y - y;
                let new_hover = menu_hit(lx, ly);
                if new_hover != hover {
                    hover = new_hover;
                    draw_menu(conn, win, gc_text, gc_hl_bg, gc_hl_text, hover);
                }
            }
            Event::ButtonRelease(ev) => {
                if first_release {
                    first_release = false;
                    continue;
                }
                let lx = ev.root_x - x;
                let ly = ev.root_y - y;
                match menu_hit(lx, ly) {
                    Some(i) => break Some(i),
                    None => break None, // click outside
                }
            }
            Event::ButtonPress(ev) if !grab_ok => {
                // Without a grab, clicks outside won't be delivered to us.
                // If the click is outside the menu, dismiss.
                let lx = ev.root_x - x;
                let ly = ev.root_y - y;
                if menu_hit(lx, ly).is_none() {
                    break None;
                }
            }
            Event::KeyPress(ev) if ev.detail == escape_keycode => {
                break None;
            }
            _ => {}
        }
    };

    // Cleanup.
    if grab_ok {
        let _ = conn.ungrab_pointer(x11rb::CURRENT_TIME);
    }
    let _ = conn.ungrab_keyboard(x11rb::CURRENT_TIME);
    let _ = conn.destroy_window(win);
    let _ = conn.free_gc(gc_text);
    let _ = conn.free_gc(gc_hl_bg);
    let _ = conn.free_gc(gc_hl_text);
    if let Some(f) = font {
        let _ = conn.close_font(f);
    }
    let _ = conn.flush();

    result.and_then(|i| MENU_ITEMS.get(i).map(|(_, a)| *a))
}

// ── Spawn tray ───────────────────────────────────────────────────────────

pub fn spawn_tray(
    tx: mpsc::SyncSender<crate::Event>,
    initial: TrayStatus,
) -> anyhow::Result<TrayHandle> {
    let (conn, screen_num) =
        RustConnection::connect(None).map_err(|e| anyhow::anyhow!("X11 connect: {e}"))?;
    let screen = conn.setup().roots[screen_num].clone();
    let atoms = Atoms::new(&conn)?.reply()?;
    let depth = screen.root_depth;

    // Find the system tray manager
    let tray_owner = conn
        .get_selection_owner(atoms._NET_SYSTEM_TRAY_S0)?
        .reply()?
        .owner;
    if tray_owner == x11rb::NONE {
        anyhow::bail!("no system tray manager found");
    }

    // Create the icon window with ParentRelative background so the
    // panel color shows through without needing a compositor.
    let win = conn.generate_id()?;
    conn.create_window(
        depth,
        win,
        screen.root,
        0,
        0,
        ICON_SIZE,
        ICON_SIZE,
        0,
        WindowClass::INPUT_OUTPUT,
        screen.root_visual,
        &CreateWindowAux::default()
            .background_pixmap(1u32) // ParentRelative
            .event_mask(
                EventMask::EXPOSURE
                    | EventMask::STRUCTURE_NOTIFY
                    | EventMask::BUTTON_PRESS,
            ),
    )?;

    // Set _XEMBED_INFO: version 0, flags XEMBED_MAPPED
    conn.change_property32(
        PropMode::REPLACE,
        win,
        atoms._XEMBED_INFO,
        atoms._XEMBED_INFO,
        &[0, XEMBED_MAPPED],
    )?;

    // Send SYSTEM_TRAY_REQUEST_DOCK to the tray manager
    conn.send_event(
        false,
        tray_owner,
        EventMask::NO_EVENT,
        ClientMessageEvent {
            response_type: CLIENT_MESSAGE_EVENT,
            format: 32,
            sequence: 0,
            window: tray_owner,
            type_: atoms._NET_SYSTEM_TRAY_OPCODE,
            data: ClientMessageData::from([
                x11rb::CURRENT_TIME,
                SYSTEM_TRAY_REQUEST_DOCK,
                win,
                0u32,
                0u32,
            ]),
        },
    )?;
    conn.flush()?;

    // Create a GC for drawing
    let gc = conn.generate_id()?;
    conn.create_gc(gc, win, &CreateGCAux::default())?;

    // Open a second connection for sending repaint signals from other threads
    let (repaint_conn, _) =
        RustConnection::connect(None).map_err(|e| anyhow::anyhow!("X11 connect: {e}"))?;

    let status = std::sync::Arc::new(Mutex::new(initial));
    let handle = TrayHandle {
        status: std::sync::Arc::clone(&status),
        repaint_conn: std::sync::Arc::new(repaint_conn),
        win,
    };

    std::thread::spawn(move || {
        let mut win_w = ICON_SIZE;
        let mut win_h = ICON_SIZE;
        // Cache composited icons keyed by background color
        let mut cached_bg: Option<(u8, u8, u8)> = None;
        let mut composited: Vec<(TrayStatus, Vec<u8>)> = Vec::new();

        loop {
            let event = match conn.wait_for_event() {
                Ok(e) => e,
                Err(_) => break,
            };
            match event {
                Event::ConfigureNotify(ev) => {
                    win_w = ev.width;
                    win_h = ev.height;
                    // Background may change on reparent/resize
                    cached_bg = None;
                }
                Event::Expose(ev) if ev.count == 0 => {
                    let s = *status.lock().unwrap();

                    // Sample background and composite icons if needed
                    let bg = sample_bg(&conn, win);
                    if cached_bg != Some(bg) {
                        composited = [
                            TrayStatus::Idle,
                            TrayStatus::Sleeping,
                            TrayStatus::Listening,
                            TrayStatus::Dictating,
                            TrayStatus::Recording,
                            TrayStatus::Processing,
                            TrayStatus::RecordingProcessing,
                        ]
                        .iter()
                        .map(|&st| (st, composite_icon(icon_rgba(st), bg.0, bg.1, bg.2)))
                        .collect();
                        cached_bg = Some(bg);
                    }

                    let data = &composited.iter().find(|(st, _)| *st == s).unwrap().1;

                    // Clear window to parent background
                    let _ = conn.clear_area(false, win, 0, 0, win_w, win_h);

                    // Blit icon centered
                    let ox = (win_w as i16 - ICON_SIZE as i16) / 2;
                    let oy = (win_h as i16 - ICON_SIZE as i16) / 2;
                    let _ = conn.put_image(
                        ImageFormat::Z_PIXMAP,
                        win,
                        gc,
                        ICON_SIZE,
                        ICON_SIZE,
                        ox,
                        oy,
                        0,
                        depth,
                        data,
                    );
                    let _ = conn.flush();
                }
                Event::ButtonPress(ev) => {
                    if ev.detail == 1 {
                        let _ = tx.send(crate::Event::Ipc(IpcCommand::Toggle));
                    } else if ev.detail == 3 {
                        if let Some(action) =
                            show_popup_menu(&conn, &screen, ev.root_x, ev.root_y)
                        {
                            let cmd = match action {
                                MenuAction::CopyLast => IpcCommand::CopyLast,
                                MenuAction::Toggle => IpcCommand::Toggle,
                                MenuAction::Exit => IpcCommand::Stop,
                            };
                            let _ = tx.send(crate::Event::Ipc(cmd));
                        }
                        // Force tray icon repaint — Expose events were consumed
                        // by the popup's nested event loop.
                        let _ = conn.clear_area(true, win, 0, 0, win_w, win_h);
                        let _ = conn.flush();
                    }
                }
                Event::DestroyNotify(ev) if ev.window == win => {
                    break;
                }
                _ => {}
            }
        }
    });

    Ok(handle)
}
