use std::sync::mpsc;
use std::sync::Mutex;
use x11rb::atom_manager;
use x11rb::connection::Connection;
use x11rb::protocol::xproto::*;
use x11rb::protocol::Event;
use x11rb::rust_connection::RustConnection;
use x11rb::wrapper::ConnectionExt as _;

use crate::IpcCommand;

const SYSTEM_TRAY_REQUEST_DOCK: u32 = 0;
const XEMBED_MAPPED: u32 = 1;
const ICON_SIZE: u16 = 24;

// Pre-rendered 24x24 RGBA icons (generated by assets/gen_icons.py).
const ICON_IDLE: &[u8] = include_bytes!("../assets/idle.rgba");
const ICON_LISTENING: &[u8] = include_bytes!("../assets/listening.rgba");
const ICON_RECORDING: &[u8] = include_bytes!("../assets/recording.rgba");
const ICON_PROCESSING: &[u8] = include_bytes!("../assets/processing.rgba");

atom_manager! {
    pub Atoms: AtomsCookie {
        _NET_SYSTEM_TRAY_OPCODE,
        _NET_SYSTEM_TRAY_S0,
        _XEMBED_INFO,
        MANAGER,
    }
}

#[derive(Clone, Copy, PartialEq)]
pub enum TrayStatus {
    Idle,
    Listening,
    Recording,
    Processing,
}

fn icon_rgba(status: TrayStatus) -> &'static [u8] {
    match status {
        TrayStatus::Idle => ICON_IDLE,
        TrayStatus::Listening => ICON_LISTENING,
        TrayStatus::Recording => ICON_RECORDING,
        TrayStatus::Processing => ICON_PROCESSING,
    }
}

/// Composite a premultiplied RGBA icon onto a background color,
/// producing X11 ZPixmap 32bpp little-endian (BGRX) output.
fn composite_icon(icon: &[u8], bg_r: u8, bg_g: u8, bg_b: u8) -> Vec<u8> {
    let mut out = Vec::with_capacity(icon.len());
    for pixel in icon.chunks_exact(4) {
        let (sr, sg, sb, sa) = (pixel[0], pixel[1], pixel[2], pixel[3]);
        let a = sa as f32 / 255.0;
        let inv = 1.0 - a;
        let r = (sr as f32 + bg_r as f32 * inv) as u8;
        let g = (sg as f32 + bg_g as f32 * inv) as u8;
        let b = (sb as f32 + bg_b as f32 * inv) as u8;
        // X11 ZPixmap 32bpp little-endian: B G R pad
        out.push(b);
        out.push(g);
        out.push(r);
        out.push(0xFF);
    }
    out
}

/// Sample the background color by reading one pixel from the cleared window.
fn sample_bg(conn: &RustConnection, win: Window) -> (u8, u8, u8) {
    conn.clear_area(false, win, 0, 0, 0, 0).ok();
    conn.flush().ok();
    if let Some(reply) = conn
        .get_image(ImageFormat::Z_PIXMAP, win, 0, 0, 1, 1, !0u32)
        .ok()
        .and_then(|c| c.reply().ok())
    {
        let d = &reply.data;
        if d.len() >= 3 {
            // ZPixmap little-endian: B G R [A]
            return (d[2], d[1], d[0]);
        }
    }
    (0, 0, 0) // fallback to black
}

// ── X11 tray handle ──────────────────────────────────────────────────────

pub struct TrayHandle {
    status: std::sync::Arc<Mutex<TrayStatus>>,
    repaint_conn: std::sync::Arc<RustConnection>,
    win: Window,
}

impl Clone for TrayHandle {
    fn clone(&self) -> Self {
        Self {
            status: std::sync::Arc::clone(&self.status),
            repaint_conn: std::sync::Arc::clone(&self.repaint_conn),
            win: self.win,
        }
    }
}

impl TrayHandle {
    pub fn update(&self, status: TrayStatus) {
        let mut s = self.status.lock().unwrap();
        if *s != status {
            *s = status;
            drop(s);
            let _ = self.repaint_conn.send_event(
                false,
                self.win,
                EventMask::EXPOSURE,
                ExposeEvent {
                    response_type: x11rb::protocol::xproto::EXPOSE_EVENT,
                    sequence: 0,
                    window: self.win,
                    x: 0,
                    y: 0,
                    width: ICON_SIZE,
                    height: ICON_SIZE,
                    count: 0,
                },
            );
            let _ = self.repaint_conn.flush();
        }
    }

    pub fn shutdown(&self) {
        let _ = self.repaint_conn.destroy_window(self.win);
        let _ = self.repaint_conn.flush();
    }
}

// ── Spawn tray ───────────────────────────────────────────────────────────

pub fn spawn_tray(
    tx: mpsc::SyncSender<crate::Event>,
    initial: TrayStatus,
) -> anyhow::Result<TrayHandle> {
    let (conn, screen_num) =
        RustConnection::connect(None).map_err(|e| anyhow::anyhow!("X11 connect: {e}"))?;
    let screen = conn.setup().roots[screen_num].clone();
    let atoms = Atoms::new(&conn)?.reply()?;
    let depth = screen.root_depth;

    // Find the system tray manager
    let tray_owner = conn
        .get_selection_owner(atoms._NET_SYSTEM_TRAY_S0)?
        .reply()?
        .owner;
    if tray_owner == x11rb::NONE {
        anyhow::bail!("no system tray manager found");
    }

    // Create the icon window with ParentRelative background so the
    // panel color shows through without needing a compositor.
    let win = conn.generate_id()?;
    conn.create_window(
        depth,
        win,
        screen.root,
        0,
        0,
        ICON_SIZE,
        ICON_SIZE,
        0,
        WindowClass::INPUT_OUTPUT,
        screen.root_visual,
        &CreateWindowAux::default()
            .background_pixmap(1u32) // ParentRelative
            .event_mask(
                EventMask::EXPOSURE
                    | EventMask::STRUCTURE_NOTIFY
                    | EventMask::BUTTON_PRESS,
            ),
    )?;

    // Set _XEMBED_INFO: version 0, flags XEMBED_MAPPED
    conn.change_property32(
        PropMode::REPLACE,
        win,
        atoms._XEMBED_INFO,
        atoms._XEMBED_INFO,
        &[0, XEMBED_MAPPED],
    )?;

    // Send SYSTEM_TRAY_REQUEST_DOCK to the tray manager
    conn.send_event(
        false,
        tray_owner,
        EventMask::NO_EVENT,
        ClientMessageEvent {
            response_type: CLIENT_MESSAGE_EVENT,
            format: 32,
            sequence: 0,
            window: tray_owner,
            type_: atoms._NET_SYSTEM_TRAY_OPCODE,
            data: ClientMessageData::from([
                x11rb::CURRENT_TIME,
                SYSTEM_TRAY_REQUEST_DOCK,
                win,
                0u32,
                0u32,
            ]),
        },
    )?;
    conn.flush()?;

    // Create a GC for drawing
    let gc = conn.generate_id()?;
    conn.create_gc(gc, win, &CreateGCAux::default())?;

    // Open a second connection for sending repaint signals from other threads
    let (repaint_conn, _) =
        RustConnection::connect(None).map_err(|e| anyhow::anyhow!("X11 connect: {e}"))?;

    let status = std::sync::Arc::new(Mutex::new(initial));
    let handle = TrayHandle {
        status: std::sync::Arc::clone(&status),
        repaint_conn: std::sync::Arc::new(repaint_conn),
        win,
    };

    std::thread::spawn(move || {
        let mut win_w = ICON_SIZE;
        let mut win_h = ICON_SIZE;
        // Cache composited icons keyed by background color
        let mut cached_bg: Option<(u8, u8, u8)> = None;
        let mut composited: Vec<(TrayStatus, Vec<u8>)> = Vec::new();

        loop {
            let event = match conn.wait_for_event() {
                Ok(e) => e,
                Err(_) => break,
            };
            match event {
                Event::ConfigureNotify(ev) => {
                    win_w = ev.width;
                    win_h = ev.height;
                    // Background may change on reparent/resize
                    cached_bg = None;
                }
                Event::Expose(ev) if ev.count == 0 => {
                    let s = *status.lock().unwrap();

                    // Sample background and composite icons if needed
                    let bg = sample_bg(&conn, win);
                    if cached_bg != Some(bg) {
                        composited = [
                            TrayStatus::Idle,
                            TrayStatus::Listening,
                            TrayStatus::Recording,
                            TrayStatus::Processing,
                        ]
                        .iter()
                        .map(|&st| (st, composite_icon(icon_rgba(st), bg.0, bg.1, bg.2)))
                        .collect();
                        cached_bg = Some(bg);
                    }

                    let data = &composited.iter().find(|(st, _)| *st == s).unwrap().1;

                    // Clear window to parent background
                    let _ = conn.clear_area(false, win, 0, 0, win_w, win_h);

                    // Blit icon centered
                    let ox = (win_w as i16 - ICON_SIZE as i16) / 2;
                    let oy = (win_h as i16 - ICON_SIZE as i16) / 2;
                    let _ = conn.put_image(
                        ImageFormat::Z_PIXMAP,
                        win,
                        gc,
                        ICON_SIZE,
                        ICON_SIZE,
                        ox,
                        oy,
                        0,
                        depth,
                        data,
                    );
                    let _ = conn.flush();
                }
                Event::ButtonPress(ev) => {
                    if ev.detail == 1 {
                        let _ = tx.send(crate::Event::Ipc(IpcCommand::Toggle));
                    } else if ev.detail == 3 {
                        let _ = tx.send(crate::Event::Ipc(IpcCommand::Stop));
                    }
                }
                Event::DestroyNotify(ev) if ev.window == win => {
                    break;
                }
                _ => {}
            }
        }
    });

    Ok(handle)
}
